language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "deploying with travis"

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: aftwitterstream
